// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crtuakzmiomymxjvxafp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydHVha3ptaW9teW14anZ4YWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTgwOTMsImV4cCI6MjA2OTE3NDA5M30.pdB3QNLSh-IAnK7OZlbJsJycuK98aVsfDNATk5elXZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});